### ISSUE TITLE
Doesnt work [FIXED]

### ISSUE THREAD

**Issue by Nathidraws** [MrCheeze/paper-mario-randomizer#1]
EDIT as of 2/2/2020:
The problem was that the rom wasnt originally .z64 I think.
Make sure the rom originally has .z64 at the end, and is called "Mario 64 (USA)" so that the program can read it.
```Paper Mario (USA).z64```
And put it in the folder with it.

___________________

It used to work perfectly, but now it doesnt seem to update the file properly.

What could be causing it?

I wonder if its just the rom..

**Comment by MrCheeze** [comment]
If you run it from cmd, is there any output?

**Comment by Nathidraws** [comment]
```
C:\Program Files (x86)\Game Files\ROMs\Nintendo 64\Paper Mario Randomizer>PM64Random.py
        1 file(s) copied.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Game Files\ROMs\Nintendo 64\Paper Mario Randomizer\PM64Random.py", line 33, in <module>
    assert(f.read(11) == b'PAPER MARIO')
AssertionError
```

**Comment by Nathidraws** [comment]
I have no clue why it doesnt work.

I try everything I can think of to try fix it, but nothing works.

**Comment by Nathidraws** [comment]
Hey.
So I downloaded the rom again and this time it was .z64

And it worked!

So I think the problem was that I possibly changed the file type to .n64 (Because I dont see whats different.), then edited your file to make it read the .n64 one.

So yeah, we can close this issue. Glad I found the issue.

**Comment by MrCheeze** [comment]
Ah, that would do it.
It's a tragedy of our time that even now there are tons in non-z64 format....
